### PR TITLE
Add spacewarps weighting

### PR DESCRIPTION
**Pull request by marten**
A followup PR next week will make this generic and then I'll move both GravSpy and Spacewarps over to that.

### CODE REVIEW

**Comment by camallen** [comment]
i did review and approve this but it was merged before i finished. 

Question - how does the assert here work when a user has not seen any subjects and have 33% chance of pulling from the training streams?
`assert Selection.select("weighted", 338, 1, 4) == [4, 3, 2, 1]`

**Comment by marten** [comment]
Sorry, wanted to get it onto staging before lunch. Tests in Designator aren't amazing, probably partly due to relative unfamiliarity with Elixir, and partly due to everything being so randomised. The tests here are mostly just running the code and checking that the output doesn't change unexpectedly when you make a code change, but there's a large degree of "assume that whatever it does now is correct, so it should keep doing that".

This module was pretty much a copy of the GoldStandard one used by Gravity Spy, but it needed different ratios per classification count, which were (and still are) hardcoded. Due to time pressure I went with a copy/paste approach for now.

**Comment by camallen** [comment]
No problems. I'm still wondering how it can always return `[4,3,2,1]`. Does it keep trying to fill the stream up and taking 1/3 from the training sets?

**Comment by marten** [comment]
Line https://github.com/zooniverse/designator/pull/44/files#diff-7353a868c26043b9ccaf09744d1e1e74R22 is setting the random seed, and with that seed it happens to return stuff in this order. It could've been `[1,2,3,4]` in a different seed.

**Comment by camallen** [comment]
Aha! thanks :mindblown:

**Pull request merged**
